    # .github/workflows/ci.yml

    name: CI/CD Pipeline

    on:
      push:
        branches:
          - master # Changed from 'main' to 'master'
      pull_request:
        branches:
          - master # Changed from 'main' to 'master'

    jobs:
      build-and-test:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write # Required to push to GitHub Container Registry

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Define image name and tag
          id: meta
          run: |
            echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> "$GITHUB_OUTPUT"
            echo "TAG=${{ github.sha }}" >> "$GITHUB_OUTPUT"

        - name: Build and push Docker image
          uses: docker/build-and-push-action@v5
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.TAG }}
              ghcr.io/${{ github.repository }}:master-latest # Changed from 'main-latest' to 'master-latest'
            file: ./Dockerfile # Assuming your Dockerfile is in the root
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Run Pytest with Coverage
          run: |
            docker run --rm ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.TAG }} \
            /bin/bash -c "pytest --cov=app --cov-report=xml"
    