name: CI/CD Pipeline

on:
  push:
    branches: [ master ] # Changed from main to master
  pull_request:
    branches: [ master ] 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image name and tag
        id: meta
        run: |
          LOWERCASE_REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$LOWERCASE_REPO_NAME" >> $GITHUB_OUTPUT
          echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
            ${{ steps.meta.outputs.IMAGE_NAME }}:master-latest
          file: ./Dockerfile
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
      
      - name: Check if /app/instance exists in container
        run: |
            docker run --rm \
              ${{ steps.meta.outputs.IMAGE_NAME }}:master-latest \
              /bin/sh -c "if [ -d /app/instance ]; then echo '/app/instance exists'; else echo '/app/instance does NOT exist'; fi && ls -l /app"   

      # In .github/workflows/ci.yml
      - name: Run Pytest with Coverage
        run: |
          docker run --rm \
            -e TESTING=True \
            -e IS_TESTING=True \
            -e WIDGET_API_KEY=test-secret-key \
            ${{ steps.meta.outputs.IMAGE_NAME }}:master-latest \
            pytest /app/tests --cov=app --cov-report=xml:/tmp/coverage.xml