name: CI/CD Pipeline

on:
  push:
    branches: [ master ] # Changed from main to master
  pull_request:
    branches: [ master ] # Changed from main to master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image name and tag
        id: meta
        run: |
          LOWERCASE_REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$LOWERCASE_REPO_NAME" >> $GITHUB_OUTPUT
          echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.IMAGE_NAME }}:${{ steps.meta.outputs.TAG }}
            ${{ steps.meta.outputs.IMAGE_NAME }}:master-latest
          file: ./Dockerfile
          #cache-from: type=gha
          #cache-to: type=gha,mode=max

      - name: Run Pytest with Coverage
        run: |
            docker run --rm \
              -e PYTHONPATH=/app \
              -e COVERAGE_FILE=/tmp/.coverage \
              -e TESTING=True \
              ${{ steps.meta.outputs.IMAGE_NAME }}:master-latest \
              pytest /app/tests --cov=app --cov-report=xml